services:
  app:
    build:
      context: .
    image: productservice
    container_name: product-service-app
    environment:
      DB_HOST: metroo-server.mysql.database.azure.com
      DB_PORT: 3306
      DB_USER: arkam
      DB_PASSWORD: Arkam@4169
      DB_NAME: product_service
    ports:
      - "8080:8080"