pipeline {
    agent any

    stages {
        stage('Build & Tag Docker Image') {
            steps {
                script {
                    withDockerRegistry(credentialsId: '4c3eb1b9-c6d4-46c8-bdef-bc9f1a1f1085', toolName: 'docker') {
                        sh "docker build -t fazlyfathhy/product_service -f Metro-Backend/product/Dockerfile ."
                    }
                }
            }
        }
        
        stage('Push Docker Image') {
            steps {
                script {
                    withDockerRegistry(credentialsId: '4c3eb1b9-c6d4-46c8-bdef-bc9f1a1f1085', toolName: 'docker') {
                        sh "docker push fazlyfathhy/product_service"
                    }
                }
            }
        }
    }
}