pipeline {
    agent any

    stages {
        stage('Debug Workspace') {
            steps {
                // Display the directory structure for debugging purposes
                sh 'ls -R "/var/lib/jenkins/workspace/Inventory Service Pipeline"'
            }
        }

        stage('Build & Tag Docker Image') {
            steps {
                script {
                    // Docker build command with dynamic tagging
                    def imageTag = "fazlyfathhy/inventory_service:${env.BUILD_NUMBER}"
                    withDockerRegistry(credentialsId: '4c3eb1b9-c6d4-46c8-bdef-bc9f1a1f1085', toolName: 'docker') {
                        sh "docker build -t ${imageTag} -f Metro-Backend/order-service/Dockerfile ."
                    }
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    // Push the tagged Docker image to the registry
                    def imageTag = "fazlyfathhy/inventory_service:${env.BUILD_NUMBER}"
                    withDockerRegistry(credentialsId: '4c3eb1b9-c6d4-46c8-bdef-bc9f1a1f1085', toolName: 'docker') {
                        sh "docker push ${imageTag}"
                    }
                }
            }
        }
    }
}
