services:
  app:
    build:
      context: .
    image: userservice
    container_name: user-service-app
    environment:
      DB_HOST: metroo-server.mysql.database.azure.com
      DB_PORT: 3306
      DB_USER: arkam
      DB_PASSWORD: Arkam@4169
      DB_NAME: user_service
    ports:
      - "8083:8083"