services:
  app:
    build:
      context: .
    image: inventoryservice
    container_name: inventory-service-app
    environment:
      DB_HOST: metroo-server.mysql.database.azure.com
      DB_PORT: 3306
      DB_USER: arkam
      DB_PASSWORD: Arkam@4169
      DB_NAME: inventory_service
    ports:
      - "8082:8082"