pipeline {
    agent any

    stages {

       stage('Debug Workspace') {
    steps {
        sh 'ls -R "/var/lib/jenkins/workspace/Inventory Service Pipeline/"'
    }
}

        stage('Build & Tag Docker Image') {
            steps {
                script {
                    withDockerRegistry(credentialsId: '4c3eb1b9-c6d4-46c8-bdef-bc9f1a1f1085', toolName: 'docker') {
                        sh """docker build -t inventory-service:latest ./inventory-service"""
                    }
                }
            }
        }
        
        stage('Push Docker Image') {
            steps {
                script {
                    withDockerRegistry(credentialsId: '4c3eb1b9-c6d4-46c8-bdef-bc9f1a1f1085', toolName: 'docker') {
                        sh "docker push fazlyfathhy/inventory_service "
                    }
                }
            }
        }
    }
}
